# Stage 1: Build the Next.js app
FROM node:18.17.0-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install 

# Copy the rest of the application code
COPY . .

# Build the Next.js application
RUN npm run build

# Stage 2: Create a minimal runtime image
FROM node:18.17.0-alpine

WORKDIR /app

# Copy only the necessary files from the build stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public

# Expose the port the Next.js app will run on
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "start"]

